### ISSUE TITLE
[BUG] <Bot Not Run>

### ISSUE THREAD

**Issue by biswajitguha01** [Spencer-0003/Ashlyn#4]
[Ashlyn] Shard 0 launched
2020-12-12T20:19:59.629602+00:00 app[worker.1]: node:internal/modules/cjs/loader:928
2020-12-12T20:19:59.629605+00:00 app[worker.1]:   throw err;
2020-12-12T20:19:59.629605+00:00 app[worker.1]:   ^
2020-12-12T20:19:59.629605+00:00 app[worker.1]: 
2020-12-12T20:19:59.629606+00:00 app[worker.1]: Error: Cannot find module 'nekos.life'
2020-12-12T20:19:59.629607+00:00 app[worker.1]: Require stack:
2020-12-12T20:19:59.629608+00:00 app[worker.1]: - /app/structures/Client.js
2020-12-12T20:19:59.629608+00:00 app[worker.1]: - /app/bot.js
2020-12-12T20:19:59.629609+00:00 app[worker.1]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
2020-12-12T20:19:59.629609+00:00 app[worker.1]:     at Function.Module._resolveFilename (/app/node_modules/module-alias/index.js:49:29)
2020-12-12T20:19:59.629610+00:00 app[worker.1]:     at Function.Module._load (node:internal/modules/cjs/loader:769:27)
2020-12-12T20:19:59.629610+00:00 app[worker.1]:     at Module.require (node:internal/modules/cjs/loader:997:19)
2020-12-12T20:19:59.629611+00:00 app[worker.1]:     at require (node:internal/modules/cjs/helpers:92:18)
2020-12-12T20:19:59.629611+00:00 app[worker.1]:     at Object.<anonymous> (/app/structures/Client.js:2:19)
2020-12-12T20:19:59.629612+00:00 app[worker.1]:     at Module._compile (node:internal/modules/cjs/loader:1108:14)
2020-12-12T20:19:59.629612+00:00 app[worker.1]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
2020-12-12T20:19:59.629612+00:00 app[worker.1]:     at Module.load (node:internal/modules/cjs/loader:973:32)
2020-12-12T20:19:59.629613+00:00 app[worker.1]:     at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
2020-12-12T20:19:59.629613+00:00 app[worker.1]:   code: 'MODULE_NOT_FOUND',
2020-12-12T20:19:59.629614+00:00 app[worker.1]:   requireStack: [ '/app/structures/Client.js', '/app/bot.js' ]
2020-12-12T20:19:59.629614+00:00 app[worker.1]: }
2020-12-12T20:19:59.644134+00:00 app[worker.1]: /app/node_modules/discord.js/src/sharding/Shard.js:158
2020-12-12T20:19:59.644136+00:00 app[worker.1]:         reject(new Error('SHARDING_READY_DIED', this.id));
2020-12-12T20:19:59.644137+00:00 app[worker.1]:                ^
2020-12-12T20:19:59.644137+00:00 app[worker.1]: 
2020-12-12T20:19:59.644139+00:00 app[worker.1]: Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.
2020-12-12T20:19:59.644140+00:00 app[worker.1]:     at Shard.onDeath (/app/node_modules/discord.js/src/sharding/Shard.js:158:16)
2020-12-12T20:19:59.644140+00:00 app[worker.1]:     at Object.onceWrapper (node:events:483:26)
2020-12-12T20:19:59.644141+00:00 app[worker.1]:     at Shard.emit (node:events:376:20)
2020-12-12T20:19:59.644141+00:00 app[worker.1]:     at Shard._handleExit (/app/node_modules/discord.js/src/sharding/Shard.js:384:10)
2020-12-12T20:19:59.644141+00:00 app[worker.1]:     at ChildProcess.emit (node:events:376:20)
2020-12-12T20:19:59.644142+00:00 app[worker.1]:     at Process.ChildProcess._handle.onexit (node:internal/child_process:284:12) {
2020-12-12T20:19:59.644142+00:00 app[worker.1]:   [Symbol(code)]: 'SHARDING_READY_DIED'
2020-12-12T20:19:59.644143+00:00 app[worker.1]: }

**Comment by Spencer-0003** [comment]
You didn't install the modules, this is done with "npm install" and by the way, you're using an older version of the bot.

**Comment by biswajitguha01** [comment]
Your script is very bug full you did not give proper package file. Sorry to say this is very bad project. Good bye.

**Comment by Spencer-0003** [comment]
The package.json file is very clearly in the repo...
